---
# tasks file for docker-install
- name: Install Atomic
  yum:
    name: atomic
    state: present

- name: Install Docker
  yum:
    #name: docker
    name: docker-1.13.1
    enablerepo: rhui-REGION-rhel-server-extras
    state: present

#todo: use lineinfile module
#- name: SED command
  #command: sed -i '/OPTIONS=.*/c\OPTIONS="--selinux-enabled --insecure-registry 172.30.0.0/16"' /etc/sysconfig/docker

#comment out for 3.7?
- name: update /etc/sysconfig/docker OPTIONS
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: "^OPTIONS=.*"
    line: "OPTIONS=\"--selinux-enabled --log-opt max-size=1M --log-opt max-file=3 --insecure-registry 172.30.0.0/16\""


- name: atomic trust add --type insecureAcceptAnything 
  shell: atomic trust add --type insecureAcceptAnything 172.30.1.1:5000
  ignore_errors: true

#- name: atomic trust add --sigstoretype atomic 1
#  shell: atomic trust add --sigstoretype atomic  --pubkeys pub@example.com 172.30.1.1:5000/production

#- name: atomic trust add --sigstoretype atomic 2
#  shell: atomic trust add --sigstoretype atomic  --pubkeys /etc/pki/example.com.pub 172.30.1.1:5000/production

#- name: atomic trust add --sigstoretype web
#  shell: atomic trust add --sigstoretype  web --sigstore https://access.redhat.com/webassets/docker/content/sigstore --pubkeys /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release registry.redhat.io
#  ignore_errors: true

- name: Enable Docker
  service:
    name: docker
    enabled: true

- name: Start Docker
  service:
    name: docker
    state: restarted
# need to add command to create and update /root/.docker/config.json
# {
#       "auths": {
#                       "registry.redhat.io": {
#                                               "auth": "cmhuLXN1cHBvcnQtYWR0YXlsb3I6cmVkaGF0MSM="
#                                                               }
#                                                                       }
#                                                                       }
