---
- hosts: aws
  name: Uninstall 3rd party tools
  become: yes
  vars:
    uninstall_3rdparty: true

  tasks:
    - name: Uninstall Git 
      yum:
        name: git
        state: absent
      when: uninstall_3rdparty == true

    - name: Uninstall Net Tools 
      yum:
        name: net-tools
        state: absent
      when: uninstall_3rdparty == true


    - name: Uninstall Bind Utils 
      yum:
        name: bind-utils
        state: absent
      when: uninstall_3rdparty == true

    - name: Uninstall IPTables Services 
      yum:
        name: iptables-services
        state: absent
      when: uninstall_3rdparty == true

    - name: Uninstall Bridge Utils 
      yum:
        name: bridge-utils
        state: absent
      when: uninstall_3rdparty == true

    - name: Uninstall Bash Completion 
      yum:
        name: bash-completion
        state: absent
      when: uninstall_3rdparty == true
